/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aghsk
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    //PARA ACCEDER A LOS METODOS DE GESTORDECONEXIONES
    GestorDeConexiones manager = new GestorDeConexiones();

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        manager.conection();

        //MOSTRAR TABLAS
        mostrarTablaPelicula();
        mostrarTablaCritica();
        mostrarTablaCritico();

        //WINDOWS LISTENER QUE DETECTA CUANDO SE CIERRA LA VENTANA 
        //SI SE CIERRA TE DESCONECTAS DE LA BBDD
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                manager.cerrarConexion();
                System.exit(0);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelPeliculas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePeliculas = new javax.swing.JTable();
        jPanelCriticas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCriticas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldid_Critica = new javax.swing.JTextField();
        jTextFieldid_Critico_Critica = new javax.swing.JTextField();
        jTextFieldTexto_Critica = new javax.swing.JTextField();
        jButtonAñadirCritica = new javax.swing.JButton();
        jTextFieldBorrarCritica = new javax.swing.JTextField();
        jButtonBorrarCritica = new javax.swing.JButton();
        jPanelCriticos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCriticos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTablePeliculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablePeliculas);

        javax.swing.GroupLayout jPanelPeliculasLayout = new javax.swing.GroupLayout(jPanelPeliculas);
        jPanelPeliculas.setLayout(jPanelPeliculasLayout);
        jPanelPeliculasLayout.setHorizontalGroup(
            jPanelPeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPeliculasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 873, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelPeliculasLayout.setVerticalGroup(
            jPanelPeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPeliculasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Peliculas", jPanelPeliculas);

        jTableCriticas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableCriticas);

        jLabel1.setText("id:");

        jLabel2.setText("Critica:");

        jLabel3.setText("id_Critico_Critica:");

        jButtonAñadirCritica.setText("Añadir Critica");
        jButtonAñadirCritica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirCriticaActionPerformed(evt);
            }
        });

        jButtonBorrarCritica.setText("Borrar");
        jButtonBorrarCritica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarCriticaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCriticasLayout = new javax.swing.GroupLayout(jPanelCriticas);
        jPanelCriticas.setLayout(jPanelCriticasLayout);
        jPanelCriticasLayout.setHorizontalGroup(
            jPanelCriticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCriticasLayout.createSequentialGroup()
                .addGroup(jPanelCriticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCriticasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(jPanelCriticasLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanelCriticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCriticasLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldid_Critico_Critica, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCriticasLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTexto_Critica, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCriticasLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldid_Critica, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jButtonAñadirCritica)
                                .addGap(130, 130, 130)
                                .addComponent(jTextFieldBorrarCritica, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonBorrarCritica)))
                        .addGap(0, 256, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelCriticasLayout.setVerticalGroup(
            jPanelCriticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCriticasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(jPanelCriticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldid_Critica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAñadirCritica)
                    .addComponent(jTextFieldBorrarCritica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBorrarCritica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCriticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldTexto_Critica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCriticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldid_Critico_Critica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Criticas", jPanelCriticas);

        jTableCriticos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableCriticos);

        javax.swing.GroupLayout jPanelCriticosLayout = new javax.swing.GroupLayout(jPanelCriticos);
        jPanelCriticos.setLayout(jPanelCriticosLayout);
        jPanelCriticosLayout.setHorizontalGroup(
            jPanelCriticosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCriticosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 873, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCriticosLayout.setVerticalGroup(
            jPanelCriticosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCriticosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(262, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Criticos", jPanelCriticos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAñadirCriticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirCriticaActionPerformed
        // BOTON AÑADIR CRITICA
        manager.insertarCritica(jTextFieldid_Critica.getText(), jTextFieldTexto_Critica.getText(), jTextFieldid_Critico_Critica.getText());
        mostrarTablaCritica();
    }//GEN-LAST:event_jButtonAñadirCriticaActionPerformed

    private void jButtonBorrarCriticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarCriticaActionPerformed
          // BOTON ELIMINAR CRITICA
          manager.eliminarCritica(jTextFieldBorrarCritica.getText());
          mostrarTablaCritica();
    }//GEN-LAST:event_jButtonBorrarCriticaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAñadirCritica;
    private javax.swing.JButton jButtonBorrarCritica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanelCriticas;
    private javax.swing.JPanel jPanelCriticos;
    private javax.swing.JPanel jPanelPeliculas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable jTableCriticas;
    private javax.swing.JTable jTableCriticos;
    private javax.swing.JTable jTablePeliculas;
    private javax.swing.JTextField jTextFieldBorrarCritica;
    private javax.swing.JTextField jTextFieldTexto_Critica;
    private javax.swing.JTextField jTextFieldid_Critica;
    private javax.swing.JTextField jTextFieldid_Critico_Critica;
    // End of variables declaration//GEN-END:variables

    private void mostrarTablaPelicula() {
        //ESTE METODO ES PARA CARGAR LOS DATOS DE LA TABLA PELICULA
        //SE CREA LA TABLA
        DefaultTableModel modelo = new DefaultTableModel();
        //AQUI SE INSERTA LA CONSULTA QUE VA EN POOLCONEXIONES
        //CONSULTA SIMPLE YA QUE COGEMOS TODOS LOS DATOS
        ResultSet rs = (ResultSet) manager.mostrarTabla("SELECT * FROM pelicula ORDER BY id_Pelicula");
        try {
            //COGEMOS LOS NOMBRES DE LA COLUMNAS
            ResultSetMetaData metaDatos = rs.getMetaData();
            int numeroColumnas = metaDatos.getColumnCount();
            String[] etiquetas = new String[numeroColumnas];
            for (int i = 0; i < numeroColumnas; i++) {
                etiquetas[i] = metaDatos.getColumnLabel(i + 1);
                modelo.setColumnIdentifiers(etiquetas);
            }
            while (rs.next()) {
                //COGEMOS LOS DATOS DE LAS FILAS
                modelo.addRow(new Object[]{rs.getString("id_Pelicula"), rs.getString("nombre_Pelicula"),
                    rs.getString("genero_Pelicula"), rs.getString("director_Pelicula"), rs.getString("duracion_Pelicula")});
            }
            //SE INSERTAN LOS DATOS EN LA TABLA
            jTablePeliculas.setModel(modelo);
            rs.close();
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
    }

    private void mostrarTablaCritica() {
        //ESTE METODO ES PARA CARGAR LOS DATOS DE LA TABLA CRITICA
        //ESTE METODO ES PARA CARGAR LOS DATOS DE LA TABLA CRITICO
        //SE CREA LA TABLA
        DefaultTableModel modelo = new DefaultTableModel();
        //AQUI SE INSERTA LA CONSULTA QUE VA EN POOLCONEXIONES
        //CONSULTA SIMPLE YA QUE COGEMOS TODOS LOS DATOS
        ResultSet rs = (ResultSet) manager.mostrarTabla("SELECT * FROM critica ORDER BY id_Critica");
        try {
            //COGEMOS LOS NOMBRES DE LA COLUMNAS
            ResultSetMetaData metaDatos = rs.getMetaData();
            int numeroColumnas = metaDatos.getColumnCount();
            String[] etiquetas = new String[numeroColumnas];
            for (int i = 0; i < numeroColumnas; i++) {
                etiquetas[i] = metaDatos.getColumnLabel(i + 1);
                modelo.setColumnIdentifiers(etiquetas);
            }
            while (rs.next()) {
                //COGEMOS LOS DATOS DE LAS FILAS
                modelo.addRow(new Object[]{rs.getString("id_Critica"), rs.getString("texto_Critica"), rs.getString("puntuacion_Critica")});
            }
            //SE INSERTAN LOS DATOS EN LA TABLA
            jTableCriticas.setModel(modelo);
            rs.close();
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
    }

    private void mostrarTablaCritico() {
        //ESTE METODO ES PARA CARGAR LOS DATOS DE LA TABLA CRITICO
        //SE CREA LA TABLA
        DefaultTableModel modelo = new DefaultTableModel();
        //AQUI SE INSERTA LA CONSULTA QUE VA EN POOLCONEXIONES
        //CONSULTA SIMPLE YA QUE COGEMOS TODOS LOS DATOS
        ResultSet rs = (ResultSet) manager.mostrarTabla("SELECT * FROM critico ORDER BY id_Critico");
        try {
            //COGEMOS LOS NOMBRES DE LA COLUMNAS
            ResultSetMetaData metaDatos = rs.getMetaData();
            int numeroColumnas = metaDatos.getColumnCount();
            String[] etiquetas = new String[numeroColumnas];
            for (int i = 0; i < numeroColumnas; i++) {
                etiquetas[i] = metaDatos.getColumnLabel(i + 1);
                modelo.setColumnIdentifiers(etiquetas);
            }
            while (rs.next()) {
                //COGEMOS LOS DATOS DE LAS FILAS
                modelo.addRow(new Object[]{rs.getString("id_Critico"), rs.getString("nombre_Critico"), rs.getString("id_Critico_Critica")});
            }
            //SE INSERTAN LOS DATOS EN LA TABLA
            jTableCriticos.setModel(modelo);
            rs.close();
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
    }

}
